# Generated by Django 6.0.3 on 2026-05-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_prifile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recommender_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
